### ISSUE TITLE
cypress-cli CI mode ignores -c option.

### ISSUE THREAD

**Issue by shauvik** [cypress-io/cypress-cli#7]
`cypress run -c integrationFolder=cypress/smoke` works on my local mac but
`cypress ci <key> -c integrationFolder=cypress/smoke` fails in my container.
It seems cypress is ignoring the -c option in CI mode.

**Comment by brian-mann** [comment]
I cannot reproduce this. I've added more tests around the CLI tool and they all pass. Additionally manually testing this does indicate that the config is being successfully modified by the `-c` or `-config` arguments.

Internally in the code there isn't much different between `cypress run` and `cypress ci`. They both parse and set config the exact same way.

What is the actual behavior / error that you're seeing that would lead you to believe that config is not being set correctly?

**Comment by brian-mann** [comment]
These arguments were being used on an older version of Cypress, which did not accept the `-c` argument.

Opening a new related issue #8 here.

**Comment by shauvik** [comment]
Thanks for the help @brian-mann
