### ISSUE TITLE
Wrong return code for cypress run on Mac

### ISSUE THREAD

**Issue by shauvik** [cypress-io/cypress-cli#9]
`cypress run` exits with a **0** return code even for failing tests on Mac OS X.

Example :
```
 24 passing (4m)
  1 pending
  5 failing
```
```
$ echo $?
0
```

This is not a problem with `cypress ci` on linux at least.

**Comment by brian-mann** [comment]
This actually is/was the intended behavior but we'll change this in the next release.

**Comment by brian-mann** [comment]
Fixed in [`0.16.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0163-06172016).
